import { 
  Patient, 
  DialysisSession, 
  DialysisChair, 
  DialysisMachine, 
  Nurse, 
  ActionableAlert, 
  AuditLog, 
  PatientMedication,
  DailyReportSummary,
  NewRegistration
} from '@/types';

export const INITIAL_REGISTRATIONS: NewRegistration[] = [
  {
    id: 'KB-REG-847291',
    full_name: 'Zulkifli bin Hashim',
    ic_number: '681120-10-5311',
    phone_number: '017-6543210',
    email: 'zulkifli68@gmail.com',
    age: 58,
    gender: 'Lelaki',
    address: 'No 45, Jalan Rinching Indah 3, 43500 Semenyih, Selangor',
    city: 'Semenyih',
    state: 'Selangor',
    patient_category: 'Pesakit Baru Dialisis',
    medical_notes: 'Mempunyai surat rujukan dari Hospital Kajang. AV Fistula di lengan left.',
    document: {
      name: 'Surat_Rujukan_Doctor_Hosp_Kajang.pdf',
      type: 'application/pdf',
      size: '1.2 MB'
    },
    sponsor_type: 'PERKESO / SOCSO',
    preferred_days: 'Isnin, Rabu, Jumaat',
    preferred_shift: 'Syif Pagi (7:00 AM)',
    assigned_chair: 'B-05',
    status: 'BARU',
    admin_notes: 'Menunggu pengesahan keputusan darah Hepatitis B/C.',
    created_at: '2026-09-28 10:15:00'
  },
  {
    id: 'KB-REG-391024',
    full_name: 'Mariam binti Ahmad',
    ic_number: '750314-10-6022',
    phone_number: '012-9988776',
    email: 'mariam.ahmad@yahoo.com',
    age: 51,
    gender: 'Perempuan',
    address: 'No 12, Taman Pelangi Semenyih, 43500 Semenyih, Selangor',
    city: 'Semenyih',
    state: 'Selangor',
    patient_category: 'Pertukaran dari Pusat Dialisis Lain',
    medical_notes: 'Tukar dari pusat dialisis Seremban kerana berpindah rumah ke Semenyih.',
    document: {
      name: 'Keputusan_Darah_Hepatitis.jpg',
      type: 'image/jpeg',
      size: '850 KB'
    },
    sponsor_type: 'Lembaga Zakat Selangor (LZS)',
    preferred_days: 'Selasa, Khamis, Sabtu',
    preferred_shift: 'Syif Tengah Hari (11:00 AM)',
    assigned_chair: 'B-09',
    status: 'DISEMAK',
    admin_notes: 'Dokumen zakat disahkan lengkap oleh pegawai LZS.',
    created_at: '2026-09-27 14:40:00'
  }
];

export const VERIFIED_CENTRE_INFO = {
  name: 'Pusat Dialisis KaizenBros',
  brand: 'KaizenBros Dialysis Centre',
  slogan: 'Kecemerlangan Rawatan Hemodialisis & Kasih Sayang Demi Kualiti Hidup Pesakit',
  kkm_license: 'KKM/BPP/2023/HD-8491',
  established_date: '15 Januari 2021',
  address: '27 & 29G, Jalan 5/10, Seksyen 5 Bandar Rinching, 43500 Semenyih, Selangor',
  phone_main: '03-87270791',
  hotline_24h: '019-338 9922',
  whatsapp_number: '60193389922',
  email: 'admin@kaizenbrosdialysis.com.my',
  operating_hours: [
    { days: 'Isnin - Sabtu', time: '6:00 Pagi - 6:00 Petang (3 Sesi: Pagi, Tengahari, Petang)' },
    { days: 'Ahad', time: 'Tutup (Kecemasan On-Call Sahaja)' }
  ],
  capacity_machines: 12,
  machine_model: 'Fresenius Medical Care 4008S NG & 5008S CorDiax (Online HDF Ready)',
  water_system: 'Sistem Rawatan Air Double Pass Reverse Osmosis (RO) Berstandard AAMI/ISO 23500',
  panels: [
    'PERKESO / SOCSO (Panel Berdaftar)',
    'JPA / KWAP (Pesara Kerajaan Malaysia)',
    'Lembaga Zakat Selangor (LZS)',
    'Baitulmal MAIWP',
    'Yayasan Buah Pinggang Kebangsaan (NKF)',
    'Insurans Swasta (Prudential, Great Eastern, AIA, Allianz, Etiqa)'
  ]
};

export const INITIAL_CHAIRS: DialysisChair[] = Array.from({ length: 12 }, (_, i) => {
  const num = (i + 1).toString().padStart(2, '0');
  const chairNo = `B-${num}`;
  const bay = i < 6 ? 'BAY_A' : i < 11 ? 'BAY_B' : 'ISOLATION';
  return {
    id: i + 1,
    chair_number: chairNo,
    bay,
    is_active: true,
    notes: i === 11 ? 'Bilik Pengasingan Khas (Hepatitis B/C Dedicated)' : `Stesen Hemodialisis ${chairNo}`
  };
});

export const INITIAL_MACHINES: DialysisMachine[] = Array.from({ length: 12 }, (_, i) => {
  const num = (i + 1).toString().padStart(2, '0');
  return {
    id: i + 1,
    serial_number: `FMC-2024-${8900 + i}`,
    brand_model: i % 3 === 0 ? 'Fresenius 5008S CorDiax (Online HDF)' : 'Fresenius 4008S NG',
    chair_id: i + 1,
    chair_number: `B-${num}`,
    online_hdf_capable: i % 3 === 0,
    status: 'OPERATIONAL',
    last_service_date: '2026-08-15',
    next_service_date: '2026-11-15'
  };
});

export const INITIAL_NURSES: Nurse[] = [
  {
    id: 1,
    user_id: 101,
    staff_id_code: 'SN-01',
    name: 'Sister Siti Fatimah binti Rahman',
    title: 'Ketua Jururawat Klinikal (Sister)',
    nursing_board_no: 'LJM-34892',
    phone: '012-3456789',
    assigned_bay: 'BAY_A',
    shift_today: 'PETANG',
    is_on_duty: true
  },
  {
    id: 2,
    user_id: 102,
    staff_id_code: 'SN-02',
    name: 'Staff Nurse Faridah binti Kassim',
    title: 'Jururawat Hemodialisis Kanan',
    nursing_board_no: 'LJM-41209',
    phone: '013-8899123',
    assigned_bay: 'BAY_B',
    shift_today: 'PETANG',
    is_on_duty: true
  },
  {
    id: 3,
    user_id: 103,
    staff_id_code: 'SN-03',
    name: 'Staff Nurse Mohd Razak bin Ismail',
    title: 'Jururawat Hemodialisis',
    nursing_board_no: 'LJM-55210',
    phone: '017-9921443',
    assigned_bay: 'BAY_A',
    shift_today: 'PETANG',
    is_on_duty: true
  }
];

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 1,
    patient_id_code: 'P00123',
    name: 'Ahmad bin Ali',
    ic_number: '580412-10-5541',
    phone: '012-9876543',
    email: 'ahmad.ali@gmail.com',
    age: 68,
    gender: 'LELAKI',
    blood_group: 'O+',
    address: 'No 45, Jalan Kesuma 3/2, Bandar Tasik Kesuma, 43700 Beranang, Selangor',
    next_of_kin_name: 'Fatimah binti Ahmad (Anak)',
    next_of_kin_phone: '019-2233445',
    next_of_kin_relation: 'Anak Perempuan',
    dry_weight_kg: 75.0,
    latest_weight_kg: 76.4,
    latest_bp: '148/82',
    vascular_access: 'AVF',
    access_location: 'Lengan Kiri (Radiocephalic AVF)',
    sponsor: 'PERKESO_SOCSO',
    sponsor_ref_no: 'SOCSO-892144',
    schedule_pattern: 'ISNIN_RABU_JUMAAT',
    preferred_shift: 'PETANG',
    assigned_chair: 'B-08',
    allergies: 'Tiada alahan ubat dilaporkan',
    comorbidities: ['Diabetes Mellitus Type 2', 'Hipertensi', 'CKD Stage 5 ESRD'],
    hepatitis_status: { hbs_ag: 'NEGATIF', anti_hcv: 'NEGATIF', hiv: 'NEGATIF' },
    is_active: true,
    created_at: '2023-04-10'
  },
  {
    id: 2,
    patient_id_code: 'P00104',
    name: 'Siti Aminah binti Yusof',
    ic_number: '620819-08-5432',
    phone: '013-4455667',
    age: 64,
    gender: 'PEREMPUAN',
    blood_group: 'A+',
    address: 'No 12, Jalan Semenyih Mewah 4, 43500 Semenyih, Selangor',
    next_of_kin_name: 'Zulkifli bin Hashim (Suami)',
    next_of_kin_phone: '012-6677889',
    next_of_kin_relation: 'Suami',
    dry_weight_kg: 58.0,
    latest_weight_kg: 59.8,
    latest_bp: '136/78',
    vascular_access: 'AVF',
    access_location: 'Lengan Kanan (Brachiocephalic AVF)',
    sponsor: 'JPA_KWAP',
    sponsor_ref_no: 'JPA-PEN-44910',
    schedule_pattern: 'ISNIN_RABU_JUMAAT',
    preferred_shift: 'PETANG',
    assigned_chair: 'B-02',
    allergies: 'Penicillin',
    comorbidities: ['Hipertensi', 'CKD Stage 5'],
    hepatitis_status: { hbs_ag: 'NEGATIF', anti_hcv: 'NEGATIF', hiv: 'NEGATIF' },
    is_active: true,
    created_at: '2023-01-15'
  },
  {
    id: 3,
    patient_id_code: 'P00115',
    name: 'Tan Ah Kow',
    ic_number: '550302-10-5123',
    phone: '016-3344551',
    age: 71,
    gender: 'LELAKI',
    blood_group: 'B+',
    address: 'No 8, Jalan Rinching 1/4, Semenyih, Selangor',
    next_of_kin_name: 'Tan Mei Ling (Anak)',
    next_of_kin_phone: '016-7788992',
    next_of_kin_relation: 'Anak Perempuan',
    dry_weight_kg: 62.5,
    latest_weight_kg: 64.2,
    latest_bp: '142/85',
    vascular_access: 'PERMACATH',
    access_location: 'Right Internal Jugular Vein (Permacath)',
    sponsor: 'ZAKAT_SELANGOR',
    schedule_pattern: 'ISNIN_RABU_JUMAAT',
    preferred_shift: 'PETANG',
    assigned_chair: 'B-04',
    comorbidities: ['Ischemic Heart Disease (IHD)', 'Hipertensi', 'ESRD'],
    hepatitis_status: { hbs_ag: 'NEGATIF', anti_hcv: 'NEGATIF', hiv: 'NEGATIF' },
    is_active: true,
    created_at: '2023-08-20'
  },
  {
    id: 4,
    patient_id_code: 'P00098',
    name: 'Muthusamy a/l Ramasamy',
    ic_number: '601114-10-6009',
    phone: '017-8899001',
    age: 65,
    gender: 'LELAKI',
    blood_group: 'O+',
    address: 'No 22, Taman Pelangi Semenyih, 43500 Semenyih, Selangor',
    next_of_kin_name: 'Priya a/p Muthusamy',
    next_of_kin_phone: '017-1122334',
    next_of_kin_relation: 'Anak Perempuan',
    dry_weight_kg: 68.0,
    latest_weight_kg: 69.8,
    latest_bp: '150/90',
    vascular_access: 'AVF',
    access_location: 'Lengan Kiri',
    sponsor: 'PERKESO_SOCSO',
    schedule_pattern: 'ISNIN_RABU_JUMAAT',
    preferred_shift: 'PETANG',
    assigned_chair: 'B-05',
    comorbidities: ['Diabetes Mellitus', 'Dyslipidemia'],
    hepatitis_status: { hbs_ag: 'NEGATIF', anti_hcv: 'NEGATIF', hiv: 'NEGATIF' },
    is_active: true,
    created_at: '2022-11-05'
  },
  {
    id: 5,
    patient_id_code: 'P00130',
    name: 'Khadijah binti Othman',
    ic_number: '590928-10-5340',
    phone: '019-3322114',
    age: 67,
    gender: 'PEREMPUAN',
    blood_group: 'AB+',
    address: 'No 5, Jalan Desa Mewah 2, 43500 Semenyih, Selangor',
    next_of_kin_name: 'Nurul Huda (Anak)',
    next_of_kin_phone: '019-4455661',
    next_of_kin_relation: 'Anak Perempuan',
    dry_weight_kg: 52.0,
    latest_weight_kg: 53.6,
    latest_bp: '130/75',
    vascular_access: 'AVF',
    access_location: 'Lengan Kiri',
    sponsor: 'BAITULMAL_MAIWP',
    schedule_pattern: 'ISNIN_RABU_JUMAAT',
    preferred_shift: 'PETANG',
    assigned_chair: 'B-06',
    comorbidities: ['Hipertensi'],
    hepatitis_status: { hbs_ag: 'NEGATIF', anti_hcv: 'NEGATIF', hiv: 'NEGATIF' },
    is_active: true,
    created_at: '2023-09-12'
  }
];

// Complete 24 Today's Patients Roster matching the prompt:
// JUMLAH PESAKIT: 24
// SUDAH HADIR: 18
// SEDANG DIALISIS: 14
// SUDAH SELESAI: 4
// BELUM HADIR: 6
export const INITIAL_TODAY_SESSIONS: DialysisSession[] = [
  // 1. Ahmad bin Ali - SEDANG DIALISIS (The primary demo patient from prompt)
  {
    id: 1,
    session_code: 'SES-20260925-08',
    patient_id: 1,
    patient_id_code: 'P00123',
    patient_name: 'Ahmad bin Ali',
    chair_id: 8,
    chair_number: 'B-08',
    machine_id: 8,
    machine_model: 'Fresenius 4008S NG',
    scheduled_date: '2026-09-25',
    scheduled_shift: 'PETANG',
    scheduled_time: '2:00 PM',
    actual_start_time: '2:05 PM',
    status: 'SEDANG_DIALISIS',
    dry_weight_kg: 75.0,
    pre_weight_kg: 76.4,
    post_weight_kg: undefined,
    target_uf_litres: 1.4,
    actual_uf_litres: 0.7,
    pre_bp: '148/82',
    current_bp: '142/80',
    dialyzer_type: 'Fresenius FX80',
    anticoagulant: 'Heparin 2000 IU bolus, 1000 IU/hr',
    nurse_in_charge: 'Staff Nurse Faridah',
    notes: 'Pesakit mengadu sedikit lenguh pinggang pada jam pertama. Tekanan darah stabil.',
    vital_signs: [
      {
        id: 101,
        dialysis_session_id: 1,
        recorded_at: '2:05 PM',
        phase: 'PRE_DIALYSIS',
        systolic_bp: 148,
        diastolic_bp: 82,
        pulse_rate: 76,
        respiratory_rate: 18,
        temperature: 36.6,
        uf_rate_ml_hr: 350,
        blood_flow_rate_qb: 280,
        dialysate_flow_rate_qd: 500,
        nurse_name: 'Staff Nurse Faridah'
      },
      {
        id: 102,
        dialysis_session_id: 1,
        recorded_at: '3:05 PM',
        phase: 'HOURLY',
        systolic_bp: 142,
        diastolic_bp: 80,
        pulse_rate: 74,
        uf_rate_ml_hr: 350,
        blood_flow_rate_qb: 280,
        dialysate_flow_rate_qd: 500,
        nurse_name: 'Staff Nurse Faridah'
      }
    ],
    created_at: '2026-09-25 14:00:00',
    updated_at: '2026-09-25 15:05:00'
  },
  // 2. Siti Aminah binti Yusof - SUDAH SELESAI (Alert: Post weight missing)
  {
    id: 2,
    session_code: 'SES-20260925-02',
    patient_id: 2,
    patient_id_code: 'P00104',
    patient_name: 'Siti Aminah binti Yusof',
    chair_id: 2,
    chair_number: 'B-02',
    machine_id: 2,
    machine_model: 'Fresenius 4008S NG',
    scheduled_date: '2026-09-25',
    scheduled_shift: 'PAGI',
    scheduled_time: '6:00 AM',
    actual_start_time: '6:10 AM',
    actual_end_time: '10:10 AM',
    status: 'SUDAH_SELESAI',
    dry_weight_kg: 58.0,
    pre_weight_kg: 59.8,
    post_weight_kg: undefined, // Intentionally left to demonstrate Alert!
    target_uf_litres: 1.8,
    actual_uf_litres: 1.8,
    pre_bp: '136/78',
    current_bp: '128/76',
    post_bp: '126/74',
    dialyzer_type: 'Fresenius FX60',
    anticoagulant: 'Clexane 40mg',
    nurse_in_charge: 'Sister Siti Fatimah',
    notes: 'Sesi selesai dengan baik tanpa kekejangan.',
    vital_signs: [],
    created_at: '2026-09-25 06:00:00',
    updated_at: '2026-09-25 10:15:00'
  },
  // 3. Tan Ah Kow - SEDANG DIALISIS (Alert: Incomplete BP check)
  {
    id: 3,
    session_code: 'SES-20260925-04',
    patient_id: 3,
    patient_id_code: 'P00115',
    patient_name: 'Tan Ah Kow',
    chair_id: 4,
    chair_number: 'B-04',
    machine_id: 4,
    machine_model: 'Fresenius 5008S CorDiax (Online HDF)',
    scheduled_date: '2026-09-25',
    scheduled_shift: 'PETANG',
    scheduled_time: '2:00 PM',
    actual_start_time: '2:15 PM',
    status: 'SEDANG_DIALISIS',
    dry_weight_kg: 62.5,
    pre_weight_kg: 64.2,
    target_uf_litres: 1.7,
    actual_uf_litres: 0.6,
    pre_bp: '142/85',
    current_bp: undefined, // Needs BP check!
    nurse_in_charge: 'Staff Nurse Mohd Razak',
    notes: 'Permacath dressing dibersihkan dengan povidone iodine.',
    vital_signs: [],
    created_at: '2026-09-25 14:10:00',
    updated_at: '2026-09-25 14:15:00'
  },
  // 4. Muthusamy a/l Ramasamy - SEDANG DIALISIS
  {
    id: 4,
    session_code: 'SES-20260925-05',
    patient_id: 4,
    patient_id_code: 'P00098',
    patient_name: 'Muthusamy a/l Ramasamy',
    chair_id: 5,
    chair_number: 'B-05',
    machine_id: 5,
    machine_model: 'Fresenius 4008S NG',
    scheduled_date: '2026-09-25',
    scheduled_shift: 'PETANG',
    scheduled_time: '2:00 PM',
    actual_start_time: '2:00 PM',
    status: 'SEDANG_DIALISIS',
    dry_weight_kg: 68.0,
    pre_weight_kg: 69.8,
    target_uf_litres: 1.8,
    actual_uf_litres: 0.8,
    pre_bp: '150/90',
    current_bp: '140/84',
    nurse_in_charge: 'Staff Nurse Faridah',
    vital_signs: [],
    created_at: '2026-09-25 14:00:00',
    updated_at: '2026-09-25 14:30:00'
  },
  // 5. Khadijah binti Othman - SEDANG DIALISIS
  {
    id: 5,
    session_code: 'SES-20260925-06',
    patient_id: 5,
    patient_id_code: 'P00130',
    patient_name: 'Khadijah binti Othman',
    chair_id: 6,
    chair_number: 'B-06',
    machine_id: 6,
    machine_model: 'Fresenius 4008S NG',
    scheduled_date: '2026-09-25',
    scheduled_shift: 'PETANG',
    scheduled_time: '2:00 PM',
    actual_start_time: '2:10 PM',
    status: 'SEDANG_DIALISIS',
    dry_weight_kg: 52.0,
    pre_weight_kg: 53.6,
    target_uf_litres: 1.6,
    actual_uf_litres: 0.5,
    pre_bp: '130/75',
    current_bp: '124/70',
    nurse_in_charge: 'Sister Siti Fatimah',
    vital_signs: [],
    created_at: '2026-09-25 14:05:00',
    updated_at: '2026-09-25 14:35:00'
  },
  // 6 - 15: Remaining SEDANG DIALISIS patients (to total 14 active)
  ...[
    { id: 6, code: 'P00088', name: 'Zainab binti Hassan', chair: 'B-01', preW: 61.2, dryW: 60.0, bp: '138/80' },
    { id: 7, code: 'P00091', name: 'Lee Chong Wei', chair: 'B-03', preW: 66.5, dryW: 65.0, bp: '144/82' },
    { id: 8, code: 'P00095', name: 'Kamal bin Ariffin', chair: 'B-07', preW: 72.0, dryW: 70.0, bp: '152/86' },
    { id: 9, code: 'P00099', name: 'Noraini binti Daud', chair: 'B-09', preW: 55.4, dryW: 54.0, bp: '126/74' },
    { id: 10, code: 'P00101', name: 'Gopal a/l Subramaniam', chair: 'B-10', preW: 78.1, dryW: 76.0, bp: '160/92' },
    { id: 11, code: 'P00108', name: 'Harun bin Salleh', chair: 'B-11', preW: 64.9, dryW: 63.5, bp: '134/78' },
    { id: 12, code: 'P00112', name: 'Mariam binti Zakaria', chair: 'B-12', preW: 50.8, dryW: 49.5, bp: '122/70' },
    { id: 13, code: 'P00118', name: 'Khoo Boon Hock', chair: 'B-01', preW: 70.3, dryW: 68.5, bp: '146/84' },
    { id: 14, code: 'P00122', name: 'Fauziah binti Idris', chair: 'B-03', preW: 57.8, dryW: 56.5, bp: '132/76' },
    { id: 15, code: 'P00125', name: 'Roslan bin Osman', chair: 'B-07', preW: 81.0, dryW: 79.0, bp: '154/88' }
  ].map((p, idx) => ({
    id: idx + 6,
    session_code: `SES-20260925-${(idx + 6).toString().padStart(2, '0')}`,
    patient_id: p.id,
    patient_id_code: p.code,
    patient_name: p.name,
    chair_id: parseInt(p.chair.replace('B-', ''), 10),
    chair_number: p.chair,
    machine_id: parseInt(p.chair.replace('B-', ''), 10),
    machine_model: 'Fresenius 4008S NG',
    scheduled_date: '2026-09-25',
    scheduled_shift: 'PETANG' as const,
    scheduled_time: '2:00 PM',
    actual_start_time: '2:10 PM',
    status: 'SEDANG_DIALISIS' as const,
    dry_weight_kg: p.dryW,
    pre_weight_kg: p.preW,
    target_uf_litres: +(p.preW - p.dryW).toFixed(1),
    actual_uf_litres: 0.6,
    pre_bp: p.bp,
    current_bp: p.bp,
    nurse_in_charge: 'Staff Nurse Faridah',
    vital_signs: [],
    created_at: '2026-09-25 14:00:00',
    updated_at: '2026-09-25 14:30:00'
  })),

  // 16, 17, 18: Remaining SUDAH SELESAI patients (to total 4 completed)
  {
    id: 16,
    session_code: 'SES-20260925-16',
    patient_id: 16,
    patient_id_code: 'P00071',
    patient_name: 'Haji Yahya bin Din',
    chair_id: 1,
    chair_number: 'B-01',
    machine_id: 1,
    machine_model: 'Fresenius 5008S CorDiax',
    scheduled_date: '2026-09-25',
    scheduled_shift: 'PAGI',
    scheduled_time: '6:00 AM',
    actual_start_time: '6:00 AM',
    actual_end_time: '10:00 AM',
    status: 'SUDAH_SELESAI',
    dry_weight_kg: 65.0,
    pre_weight_kg: 66.8,
    post_weight_kg: 65.1,
    target_uf_litres: 1.8,
    actual_uf_litres: 1.7,
    pre_bp: '140/80',
    post_bp: '130/76',
    nurse_in_charge: 'Sister Siti Fatimah',
    vital_signs: [],
    created_at: '2026-09-25 06:00:00',
    updated_at: '2026-09-25 10:05:00'
  },
  {
    id: 17,
    session_code: 'SES-20260925-17',
    patient_id: 17,
    patient_id_code: 'P00075',
    patient_name: 'Chew Siew Kuan',
    chair_id: 3,
    chair_number: 'B-03',
    machine_id: 3,
    machine_model: 'Fresenius 4008S NG',
    scheduled_date: '2026-09-25',
    scheduled_shift: 'PAGI',
    scheduled_time: '6:00 AM',
    actual_start_time: '6:05 AM',
    actual_end_time: '10:05 AM',
    status: 'SUDAH_SELESAI',
    dry_weight_kg: 54.0,
    pre_weight_kg: 55.6,
    post_weight_kg: 54.0,
    target_uf_litres: 1.6,
    actual_uf_litres: 1.6,
    pre_bp: '132/78',
    post_bp: '124/72',
    nurse_in_charge: 'Staff Nurse Faridah',
    vital_signs: [],
    created_at: '2026-09-25 06:00:00',
    updated_at: '2026-09-25 10:10:00'
  },
  {
    id: 18,
    session_code: 'SES-20260925-18',
    patient_id: 18,
    patient_id_code: 'P00080',
    patient_name: 'Salbiah binti Hamzah',
    chair_id: 6,
    chair_number: 'B-06',
    machine_id: 6,
    machine_model: 'Fresenius 4008S NG',
    scheduled_date: '2026-09-25',
    scheduled_shift: 'PAGI',
    scheduled_time: '6:00 AM',
    actual_start_time: '6:15 AM',
    actual_end_time: '10:15 AM',
    status: 'SUDAH_SELESAI',
    dry_weight_kg: 60.0,
    pre_weight_kg: 61.9,
    post_weight_kg: 60.1,
    target_uf_litres: 1.9,
    actual_uf_litres: 1.8,
    pre_bp: '144/82',
    post_bp: '130/78',
    nurse_in_charge: 'Staff Nurse Mohd Razak',
    vital_signs: [],
    created_at: '2026-09-25 06:00:00',
    updated_at: '2026-09-25 10:20:00'
  },

  // 19 - 24: BELUM HADIR patients (to total 6 pending)
  {
    id: 19,
    session_code: 'SES-20260925-19',
    patient_id: 19,
    patient_id_code: 'P00140',
    patient_name: 'Ismail bin Abdullah',
    chair_id: 8,
    chair_number: 'B-08',
    machine_id: 8,
    machine_model: 'Fresenius 4008S NG',
    scheduled_date: '2026-09-25',
    scheduled_shift: 'PETANG',
    scheduled_time: '2:30 PM',
    status: 'BELUM_HADIR',
    dry_weight_kg: 70.0,
    nurse_in_charge: 'Staff Nurse Faridah',
    vital_signs: [],
    created_at: '2026-09-25 13:00:00',
    updated_at: '2026-09-25 13:00:00'
  },
  {
    id: 20,
    session_code: 'SES-20260925-20',
    patient_id: 20,
    patient_id_code: 'P00142',
    patient_name: 'Noor Haliza binti Mansor',
    chair_id: 9,
    chair_number: 'B-09',
    machine_id: 9,
    machine_model: 'Fresenius 4008S NG',
    scheduled_date: '2026-09-25',
    scheduled_shift: 'PETANG',
    scheduled_time: '2:30 PM',
    status: 'BELUM_HADIR',
    dry_weight_kg: 56.5,
    nurse_in_charge: 'Sister Siti Fatimah',
    vital_signs: [],
    created_at: '2026-09-25 13:00:00',
    updated_at: '2026-09-25 13:00:00'
  },
  {
    id: 21,
    session_code: 'SES-20260925-21',
    patient_id: 21,
    patient_id_code: 'P00145',
    patient_name: 'Chong Yee Kuan',
    chair_id: 10,
    chair_number: 'B-10',
    machine_id: 10,
    machine_model: 'Fresenius 4008S NG',
    scheduled_date: '2026-09-25',
    scheduled_shift: 'PETANG',
    scheduled_time: '3:00 PM',
    status: 'BELUM_HADIR',
    dry_weight_kg: 67.0,
    nurse_in_charge: 'Staff Nurse Mohd Razak',
    vital_signs: [],
    created_at: '2026-09-25 13:00:00',
    updated_at: '2026-09-25 13:00:00'
  },
  {
    id: 22,
    session_code: 'SES-20260925-22',
    patient_id: 22,
    patient_id_code: 'P00148',
    patient_name: 'Devan a/l Krishnan',
    chair_id: 11,
    chair_number: 'B-11',
    machine_id: 11,
    machine_model: 'Fresenius 4008S NG',
    scheduled_date: '2026-09-25',
    scheduled_shift: 'PETANG',
    scheduled_time: '3:00 PM',
    status: 'BELUM_HADIR',
    dry_weight_kg: 74.0,
    nurse_in_charge: 'Staff Nurse Faridah',
    vital_signs: [],
    created_at: '2026-09-25 13:00:00',
    updated_at: '2026-09-25 13:00:00'
  },
  {
    id: 23,
    session_code: 'SES-20260925-23',
    patient_id: 23,
    patient_id_code: 'P00150',
    patient_name: 'Hasnah binti Mat Noor',
    chair_id: 12,
    chair_number: 'B-12',
    machine_id: 12,
    machine_model: 'Fresenius 4008S NG',
    scheduled_date: '2026-09-25',
    scheduled_shift: 'PETANG',
    scheduled_time: '3:00 PM',
    status: 'BELUM_HADIR',
    dry_weight_kg: 51.5,
    nurse_in_charge: 'Sister Siti Fatimah',
    vital_signs: [],
    created_at: '2026-09-25 13:00:00',
    updated_at: '2026-09-25 13:00:00'
  },
  {
    id: 24,
    session_code: 'SES-20260925-24',
    patient_id: 24,
    patient_id_code: 'P00155',
    patient_name: 'Zulkarnain bin Ahmad',
    chair_id: 2,
    chair_number: 'B-02',
    machine_id: 2,
    machine_model: 'Fresenius 4008S NG',
    scheduled_date: '2026-09-25',
    scheduled_shift: 'PETANG',
    scheduled_time: '3:15 PM',
    status: 'BELUM_HADIR',
    dry_weight_kg: 82.0,
    nurse_in_charge: 'Staff Nurse Mohd Razak',
    vital_signs: [],
    created_at: '2026-09-25 13:00:00',
    updated_at: '2026-09-25 13:00:00'
  }
];

export const INITIAL_ACTIONABLE_ALERTS: ActionableAlert[] = [
  {
    id: 1,
    patient_id: 1,
    patient_name: 'Ahmad bin Ali',
    chair_number: 'B-08',
    session_id: 1,
    alert_type: 'BP_INCOMPLETE',
    message: 'Ahmad bin Ali: Rekod tekanan darah jam ke-2 masih belum diambil',
    severity: 'WARNING',
    is_resolved: false,
    created_at: '3:05 PM'
  },
  {
    id: 2,
    patient_id: 2,
    patient_name: 'Siti Aminah binti Yusof',
    chair_number: 'B-02',
    session_id: 2,
    alert_type: 'POST_WEIGHT_MISSING',
    message: 'Siti Aminah: Berat selepas dialisis belum direkodkan',
    severity: 'CRITICAL',
    is_resolved: false,
    created_at: '10:15 AM'
  },
  {
    id: 3,
    patient_id: 3,
    patient_name: 'Tan Ah Kow',
    chair_number: 'B-04',
    session_id: 3,
    alert_type: 'BP_INCOMPLETE',
    message: 'Tan Ah Kow: BP semasa dialisis belum lengkap',
    severity: 'WARNING',
    is_resolved: false,
    created_at: '2:45 PM'
  }
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 1,
    user_name: 'Staff Nurse Faridah',
    user_role: 'STAFF_NURSE',
    action: 'MULAKAN_SESI',
    entity_type: 'dialysis_sessions',
    entity_id: 1,
    details: 'Check-in pesakit Ahmad bin Ali (P00123) di kerusi B-08, Berat: 76.4kg, BP: 148/82',
    ip_address: '192.168.1.42',
    created_at: '2026-09-25 14:05:12'
  },
  {
    id: 2,
    user_name: 'Sister Siti Fatimah',
    user_role: 'HEAD_NURSE',
    action: 'TAMATKAN_SESI',
    entity_type: 'dialysis_sessions',
    entity_id: 2,
    details: 'Selesai sesi Siti Aminah (P00104) di kerusi B-02, UF: 1.8L',
    ip_address: '192.168.1.10',
    created_at: '2026-09-25 10:10:45'
  },
  {
    id: 3,
    user_name: 'Dr. Azman bin Khairuddin',
    user_role: 'NEPHROLOGIST',
    action: 'KEMASKINI_BERAT_KERING',
    entity_type: 'patients',
    entity_id: 1,
    details: 'Pelarasan berat kering Ahmad bin Ali dari 75.5kg ke 75.0kg selepas klinikal re-evaluation',
    ip_address: '192.168.1.5',
    created_at: '2026-09-24 16:30:00'
  },
  {
    id: 4,
    user_name: 'Admin Pentadbir',
    user_role: 'ADMIN',
    action: 'LOG_MASUK',
    entity_type: 'users',
    entity_id: 1,
    details: 'Log masuk pentadbir ke sistem KaizenBros Web Console',
    ip_address: '192.168.1.1',
    created_at: '2026-09-25 07:45:00'
  }
];

export const INITIAL_PATIENT_MEDICATIONS: PatientMedication[] = [
  {
    id: 1,
    patient_id: 1,
    medication_id: 1,
    medication_name: 'Erythropoietin (EPO / Recormon)',
    dosage: '4,000 IU',
    frequency: '1x seminggu (Sesi Jumaat)',
    route: 'SUBCUTANEOUS',
    is_active: true
  },
  {
    id: 2,
    patient_id: 1,
    medication_id: 2,
    medication_name: 'Venofer (Iron Sucrose)',
    dosage: '100 mg IV',
    frequency: '2 minggu sekali semasa dialisis',
    route: 'IV',
    is_active: true
  },
  {
    id: 3,
    patient_id: 1,
    medication_id: 3,
    medication_name: 'Calcium Carbonate',
    dosage: '500 mg',
    frequency: '3x sehari bersama hidangan utama (Phosphate Binder)',
    route: 'ORAL',
    is_active: true
  },
  {
    id: 4,
    patient_id: 1,
    medication_id: 4,
    medication_name: 'Amlodipine',
    dosage: '10 mg',
    frequency: '1x sehari setiap malam (Tekanan Darah)',
    route: 'ORAL',
    is_active: true
  },
  {
    id: 5,
    patient_id: 1,
    medication_id: 5,
    medication_name: 'B-Complex & Folic Acid',
    dosage: '1 tablet',
    frequency: '1x sehari pagi (Vitamin Buah Pinggang)',
    route: 'ORAL',
    is_active: true
  }
];

export const INITIAL_DAILY_SUMMARY: DailyReportSummary = {
  date: '2026-09-25',
  total_patients: 24,
  attended: 18,
  in_progress: 14,
  completed: 4,
  pending: 6,
  no_show: 0,
  cancelled: 0,
  total_fluid_removed_litres: 28.4
};
